spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL:jdbc:h2:mem:ebi}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:changeit}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
